env: dev
port: 8085

auth:
  endpoint: "http://localhost:8084"

endpoint_configuration:
  - live_endpoint: "http://localhost:8086" # user service
    live_timeout_sec: 60
    gw_endpoint: "/v1/users"
    rate_limit_req_per_sec: 5
  - live_endpoint: "http://localhost:8086" # user service
    live_timeout_sec: 60
    gw_endpoint: "/v1/users/??/contact"
    rate_limit_req_per_sec: 5
  - live_endpoint: "http://localhost:8087" # orders service
    live_timeout_sec: 60
    gw_endpoint: "/v1/orders"
    rate_limit_req_per_sec: 5
  - live_endpoint: "http://localhost:8087" # orders service
    live_timeout_sec: 60
    gw_endpoint: "/v1/orders/??/details"
    rate_limit_req_per_sec: 5
