env: dev
port: 8084

db:
  host: "localhost"
  port: 5435
  name: "auth"
  user: "app"
  password: "app"
  sslmode: "disable"
  timezone: "UTC"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime_sec: 1800
  conn_max_idle_time_sec: 300

redis:
  host: "localhost"
  port: 6389
  password: ""
  db: 0
